const QUICK_RANDOMIZER_DEFAULTS = {
  inputMode: 'names',
  groupingMode: 'groupCount',
  groupingValue: 4,
  sessions: 1,
  advancedOpen: false,
  balanceAttributeKey: null,
  keepTogetherInput: '',
  avoidPairingsInput: '',
};

const NETWORKING_DEFAULTS = {
  ...QUICK_RANDOMIZER_DEFAULTS,
  sessions: 3,
};

const MULTI_ROUND_DEFAULTS = {
  ...QUICK_RANDOMIZER_DEFAULTS,
  groupingMode: 'groupSize',
  groupingValue: 4,
  sessions: 4,
  advancedOpen: true,
};

const TECHNICAL_CSV_DEFAULTS = {
  ...QUICK_RANDOMIZER_DEFAULTS,
  inputMode: 'csv',
  groupingMode: 'groupSize',
  groupingValue: 4,
  sessions: 3,
  advancedOpen: true,
  balanceAttributeKey: 'role',
};

const CONSTRAINT_CSV_DEFAULTS = {
  ...TECHNICAL_CSV_DEFAULTS,
  keepTogetherInput: 'Alex, Sam',
  avoidPairingsInput: 'Priya, Jordan',
};

const SOCIAL_GOLFER_DEFAULTS = {
  ...QUICK_RANDOMIZER_DEFAULTS,
  groupingMode: 'groupSize',
  groupingValue: 4,
  sessions: 5,
  advancedOpen: true,
};

export const TOOL_PAGE_DEFINITIONS_DATA = {
  home: {
    key: 'home',
    slug: '',
    mode: 'quick-randomizer',
    sectionSet: 'standard',
    defaultPreset: 'random',
    quickSetupDefaults: QUICK_RANDOMIZER_DEFAULTS,
    liveLocales: ['en', 'de', 'es', 'fr', 'ja', 'hi', 'zh'],
    experiment: {
      label: 'english-home-random-group',
      futureVariants: ['headline-scenario-first', 'cta-tool-vs-optimizer'],
    },
    inventory: {
      searchIntent: 'random group generator',
      audience: 'teachers, facilitators, and event organizers',
      priority: 'primary',
      rolloutStage: 'live',
    },
  },
  'random-group-generator': {
    key: 'random-group-generator',
    slug: 'random-group-generator',
    mode: 'quick-randomizer',
    sectionSet: 'standard',
    defaultPreset: 'random',
    quickSetupDefaults: QUICK_RANDOMIZER_DEFAULTS,
    liveLocales: ['en', 'de', 'es', 'fr', 'ja', 'hi', 'zh'],
    experiment: {
      label: 'english-random-group-core',
      futureVariants: ['hero-speed-vs-fairness', 'faq-short-vs-long'],
    },
    inventory: {
      searchIntent: 'random group generator',
      audience: 'teachers, facilitators, and workshop hosts',
      priority: 'primary',
      rolloutStage: 'live',
    },
  },
  'random-team-generator': {
    key: 'random-team-generator',
    slug: 'random-team-generator',
    mode: 'quick-randomizer',
    sectionSet: 'standard',
    defaultPreset: 'balanced',
    quickSetupDefaults: QUICK_RANDOMIZER_DEFAULTS,
    liveLocales: ['en', 'de', 'es', 'fr', 'ja', 'hi', 'zh'],
    experiment: {
      label: 'english-random-team-balance',
      futureVariants: ['team-fairness-hero', 'cta-balance-emphasis'],
    },
    inventory: {
      searchIntent: 'random team generator',
      audience: 'coaches, facilitators, and managers',
      priority: 'primary',
      rolloutStage: 'live',
    },
  },
  'random-pair-generator': {
    key: 'random-pair-generator',
    slug: 'random-pair-generator',
    mode: 'quick-randomizer',
    sectionSet: 'standard',
    defaultPreset: 'random',
    quickSetupDefaults: { ...QUICK_RANDOMIZER_DEFAULTS, groupingMode: 'groupSize', groupingValue: 2 },
    liveLocales: ['en'],
    experiment: {
      label: 'english-random-pair-partners',
      futureVariants: ['pairing-speed-hero', 'rotation-proof-points'],
    },
    inventory: {
      searchIntent: 'random pair generator',
      audience: 'teachers, trainers, and facilitators running partner activities',
      priority: 'primary',
      rolloutStage: 'live',
    },
  },
  'team-shuffle-generator': {
    key: 'team-shuffle-generator',
    slug: 'team-shuffle-generator',
    mode: 'quick-randomizer',
    sectionSet: 'standard',
    defaultPreset: 'balanced',
    quickSetupDefaults: QUICK_RANDOMIZER_DEFAULTS,
    liveLocales: ['en'],
    experiment: {
      label: 'english-team-shuffle-remix',
      futureVariants: ['remix-language-vs-balance-language', 'fairness-chip-order'],
    },
    inventory: {
      searchIntent: 'team shuffle generator',
      audience: 'coaches, managers, and workshop facilitators',
      priority: 'supporting',
      rolloutStage: 'live',
    },
  },
  'breakout-room-generator': {
    key: 'breakout-room-generator',
    slug: 'breakout-room-generator',
    mode: 'multi-round',
    sectionSet: 'standard',
    defaultPreset: 'networking',
    quickSetupDefaults: NETWORKING_DEFAULTS,
    liveLocales: ['en', 'de', 'es', 'fr', 'ja', 'hi', 'zh'],
    experiment: {
      label: 'english-breakout-room-rotation',
      futureVariants: ['remote-call-proof', 'multi-round-emphasis'],
    },
    inventory: {
      searchIntent: 'breakout room generator',
      audience: 'remote facilitators and workshop hosts',
      priority: 'primary',
      rolloutStage: 'live',
    },
  },
  'workshop-group-generator': {
    key: 'workshop-group-generator',
    slug: 'workshop-group-generator',
    mode: 'quick-randomizer',
    sectionSet: 'standard',
    defaultPreset: 'balanced',
    quickSetupDefaults: QUICK_RANDOMIZER_DEFAULTS,
    liveLocales: ['en', 'de', 'es', 'fr', 'ja', 'hi', 'zh'],
    experiment: {
      label: 'english-workshop-groups-facilitator',
      futureVariants: ['workshop-outcomes-hero', 'multi-round-vs-constraint-copy'],
    },
    inventory: {
      searchIntent: 'workshop group generator',
      audience: 'workshop facilitators and training teams',
      priority: 'primary',
      rolloutStage: 'live',
    },
  },
  'student-group-generator': {
    key: 'student-group-generator',
    slug: 'student-group-generator',
    mode: 'quick-randomizer',
    sectionSet: 'standard',
    defaultPreset: 'balanced',
    quickSetupDefaults: QUICK_RANDOMIZER_DEFAULTS,
    liveLocales: ['en', 'de', 'es', 'fr', 'ja', 'hi', 'zh'],
    experiment: {
      label: 'english-student-group-teacher',
      futureVariants: ['teacher-proof-points', 'classroom-management-copy'],
    },
    inventory: {
      searchIntent: 'student group generator',
      audience: 'teachers and school staff',
      priority: 'primary',
      rolloutStage: 'live',
    },
  },
  'icebreaker-group-generator': {
    key: 'icebreaker-group-generator',
    slug: 'icebreaker-group-generator',
    mode: 'quick-randomizer',
    sectionSet: 'standard',
    defaultPreset: 'networking',
    quickSetupDefaults: NETWORKING_DEFAULTS,
    liveLocales: ['en'],
    experiment: {
      label: 'english-icebreaker-quick-groups',
      futureVariants: ['warmup-language-vs-networking-language', 'short-vs-detailed-subhead'],
    },
    inventory: {
      searchIntent: 'icebreaker group generator',
      audience: 'facilitators, teachers, and event hosts',
      priority: 'supporting',
      rolloutStage: 'live',
    },
  },
  'speed-networking-generator': {
    key: 'speed-networking-generator',
    slug: 'speed-networking-generator',
    mode: 'multi-round',
    sectionSet: 'standard',
    defaultPreset: 'networking',
    quickSetupDefaults: NETWORKING_DEFAULTS,
    liveLocales: ['en', 'de', 'es', 'fr', 'ja', 'hi', 'zh'],
    experiment: {
      label: 'english-speed-networking-rounds',
      futureVariants: ['repeat-pairing-emphasis', 'event-format-proof'],
    },
    inventory: {
      searchIntent: 'speed networking generator',
      audience: 'event organizers and community hosts',
      priority: 'primary',
      rolloutStage: 'live',
    },
  },
  'group-generator-with-constraints': {
    key: 'group-generator-with-constraints',
    slug: 'group-generator-with-constraints',
    mode: 'constraint-optimizer',
    sectionSet: 'standard',
    defaultPreset: 'balanced',
    quickSetupDefaults: CONSTRAINT_CSV_DEFAULTS,
    liveLocales: ['en'],
    experiment: {
      label: 'english-constraints-power',
      futureVariants: ['rules-first-hero', 'advanced-workspace-bridge'],
    },
    inventory: {
      searchIntent: 'group generator with constraints',
      audience: 'facilitators and planners with assignment rules',
      priority: 'supporting',
      rolloutStage: 'live',
    },
  },
  'multi-round-group-assignment-tool': {
    key: 'multi-round-group-assignment-tool',
    slug: 'multi-round-group-assignment-tool',
    mode: 'multi-round',
    sectionSet: 'technical',
    defaultPreset: 'networking',
    quickSetupDefaults: MULTI_ROUND_DEFAULTS,
    liveLocales: ['en'],
    experiment: {
      label: 'english-technical-multi-round-assignment',
      futureVariants: ['constraint-first-hero', 'example-first-section'],
    },
    inventory: {
      searchIntent: 'multi-round group assignment tool with constraints',
      audience: 'facilitators, instructors, and event planners running repeated sessions',
      priority: 'supporting',
      rolloutStage: 'live',
    },
  },
  'group-assignment-optimizer': {
    key: 'group-assignment-optimizer',
    slug: 'group-assignment-optimizer',
    mode: 'constraint-optimizer',
    sectionSet: 'technical',
    defaultPreset: 'balanced',
    quickSetupDefaults: TECHNICAL_CSV_DEFAULTS,
    liveLocales: ['en'],
    experiment: {
      label: 'english-technical-group-assignment-optimizer',
      futureVariants: ['solver-language-vs-planner-language', 'hard-soft-constraints-copy'],
    },
    inventory: {
      searchIntent: 'group assignment optimizer',
      audience: 'people who need optimized assignments rather than random shuffles',
      priority: 'supporting',
      rolloutStage: 'live',
    },
  },
  'social-golfer-problem-solver': {
    key: 'social-golfer-problem-solver',
    slug: 'social-golfer-problem-solver',
    mode: 'social-golfer',
    sectionSet: 'technical',
    defaultPreset: 'networking',
    quickSetupDefaults: SOCIAL_GOLFER_DEFAULTS,
    liveLocales: ['en'],
    experiment: {
      label: 'english-technical-social-golfer',
      futureVariants: ['events-language-vs-classic-problem-language', 'minimal-repeat-hero'],
    },
    inventory: {
      searchIntent: 'social golfer problem solver',
      audience: 'event hosts and organizers planning repeated small-group rounds',
      priority: 'supporting',
      rolloutStage: 'live',
    },
  },
  'constraint-based-team-generator': {
    key: 'constraint-based-team-generator',
    slug: 'constraint-based-team-generator',
    mode: 'constraint-optimizer',
    sectionSet: 'technical',
    defaultPreset: 'balanced',
    quickSetupDefaults: CONSTRAINT_CSV_DEFAULTS,
    liveLocales: ['en'],
    experiment: {
      label: 'english-technical-constraint-based-team-generator',
      futureVariants: ['team-generator-copy', 'constraint-list-above-fold'],
    },
    inventory: {
      searchIntent: 'constraint based team generator',
      audience: 'teachers, facilitators, and managers balancing teams with rules',
      priority: 'supporting',
      rolloutStage: 'live',
    },
  },
};
