use serde::Deserialize;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Deserialize, Default)]
struct FixtureSummary {
    #[serde(default)]
    metadata: FixtureMetadata,
}

#[derive(Deserialize, Default)]
struct FixtureMetadata {
    #[serde(default)]
    tags: Vec<String>,
    #[serde(default)]
    kind: FixtureKind,
    #[serde(default)]
    tier: FixtureTier,
}

#[derive(Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
enum FixtureKind {
    #[default]
    Correctness,
    Performance,
}

#[derive(Deserialize, Default, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
enum FixtureTier {
    #[default]
    Default,
    Slow,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let fixtures_dir = manifest_dir.join("tests").join("test_cases");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", fixtures_dir.display());

    let mut fixture_paths = fs::read_dir(&fixtures_dir)
        .unwrap()
        .filter_map(|entry| entry.ok().map(|entry| entry.path()))
        .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("json"))
        .collect::<Vec<_>>();
    fixture_paths.sort();

    let mut generated = String::from("// @generated by solver-core/build.rs\n\n");

    for fixture_path in fixture_paths {
        println!("cargo:rerun-if-changed={}", fixture_path.display());

        let summary: FixtureSummary = serde_json::from_str(
            &fs::read_to_string(&fixture_path).unwrap(),
        )
        .unwrap_or_else(|error| {
            panic!(
                "Failed to parse fixture {}: {error}",
                fixture_path.display()
            )
        });

        let fn_name = make_test_name(&fixture_path, &summary.metadata.tags);
        let path_literal = fixture_path.to_string_lossy();
        let should_ignore = summary.metadata.kind == FixtureKind::Performance
            || summary.metadata.tier == FixtureTier::Slow;

        generated.push_str("#[allow(non_snake_case)]\n#[test]\n");
        if should_ignore {
            generated.push_str("#[ignore]\n");
        }
        generated.push_str(&format!(
            "fn {fn_name}() {{\n    run_fixture_case(Path::new(r#\"{path_literal}\"#));\n}}\n\n"
        ));
    }

    fs::write(out_dir.join("generated_data_driven_cases.rs"), generated).unwrap();
}

fn make_test_name(path: &Path, tags: &[String]) -> String {
    let mut parts = vec!["case".to_string()];
    for tag in tags {
        let sanitized = sanitize_identifier(tag);
        if !sanitized.is_empty() && !parts.contains(&sanitized) {
            parts.push(sanitized);
        }
    }

    let stem = path
        .file_stem()
        .and_then(|stem| stem.to_str())
        .expect("fixture file without stem");
    parts.push(sanitize_identifier(stem));
    parts.join("__")
}

fn sanitize_identifier(input: &str) -> String {
    let mut output = String::with_capacity(input.len());
    let mut last_was_underscore = false;

    for ch in input.chars() {
        let normalized = if ch.is_ascii_alphanumeric() {
            ch.to_ascii_lowercase()
        } else {
            '_'
        };

        if normalized == '_' {
            if !last_was_underscore && !output.is_empty() {
                output.push('_');
            }
            last_was_underscore = true;
        } else {
            output.push(normalized);
            last_was_underscore = false;
        }
    }

    output.trim_matches('_').to_string()
}
